# Generated by Django 5.1.5 on 2025-02-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='postfilemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(max_length=20)),
                ('filetopic', models.CharField(max_length=20)),
                ('filedescription', models.CharField(max_length=200)),
                ('fileupload', models.FileField(blank=True, null=True, upload_to='learnapp/static/files/')),
            ],
        ),
        migrations.CreateModel(
            name='postvideomodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(max_length=20)),
                ('videotopic', models.CharField(max_length=20)),
                ('videodescription', models.CharField(max_length=200)),
                ('videoupload', models.FileField(blank=True, null=True, upload_to='learnapp/static/videos/')),
            ],
        ),
    ]
