# Generated by Django 5.1.5 on 2025-02-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0006_alter_postfilemodel_fileupload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfilemodel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
