# Generated by Django 5.1.5 on 2025-02-06 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0007_postfilemodel_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfilemodel',
            name='thumbnail',
        ),
    ]
