# Generated by Django 5.1.5 on 2025-02-07 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0010_responsemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsemodel',
            name='username',
        ),
    ]
