# Generated by Django 5.1.5 on 2025-02-07 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0011_remove_responsemodel_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='responsemodel',
        ),
    ]
