# Generated by Django 5.1.5 on 2025-02-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0012_delete_responsemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='responsemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('response', models.TextField()),
                ('teachername', models.CharField(max_length=20)),
                ('videotopic', models.CharField(max_length=20)),
                ('videodescription', models.TextField()),
            ],
        ),
    ]
